const mongoose = require("mongoose");

const imageSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    originalName: { type: String, trim: true },
  },
  { _id: false }
);

const memorySchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 200,
    },

    date: {
      type: Date,
    },

    location: {
      type: String,
      trim: true,
      maxlength: 200,
    },

    people: [
      {
        type: String,
        trim: true,
      },
    ],

    description: {
      type: String,
      required: true,
      trim: true,
    },

    images: [imageSchema],

    /*
      Only 3 creation modules:
      1. Story Book
      2. Poetry
      3. Magazine

      "short-book" is no longer a separate module.
      Chapter Book is handled inside Story Book.
    */
    outputType: {
      type: String,
      enum: ["story", "poetry", "magazine"],
      required: true,
    },

    generatedTitle: {
      type: String,
      trim: true,
    },

    /*
      Structured AI output is stored as JSON string so
      existing frontend/API compatibility remains simple.
    */
    generatedContent: {
      type: String,
    },

    /*
      Optional structured metadata generated by AI.
      This makes future renderer/layout improvements easier.
    */
    generatedData: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    status: {
      type: String,
      enum: ["draft", "generated"],
      default: "draft",
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("Memory", memorySchema);